# Generated by Django 3.0.5 on 2020-07-20 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='link_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p1_10',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p1_11',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p1_12',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p1_13',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p1_14',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p1_15',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p1_16',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p1_17',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p1_18',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p1_19',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p1_20',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p1_6',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p1_7',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p1_8',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p1_9',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p2_10',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p2_6',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p2_7',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p2_8',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p2_9',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p3_10',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p3_6',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p3_7',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p3_8',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p3_9',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p4_10',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p4_6',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p4_7',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p4_8',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p4_9',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p5_10',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p5_6',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p5_7',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p5_8',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p5_9',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p6_10',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p6_6',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p6_7',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p6_8',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p6_9',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p7_10',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p7_6',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p7_7',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p7_8',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p7_9',
        ),
        migrations.AddField(
            model_name='post',
            name='img1_2',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='img1_3',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='img1_4',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='img1_5',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='img2_2',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='img2_3',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='img2_4',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='img2_5',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='img3_2',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='img3_3',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='img3_4',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='img3_5',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='img4_2',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='img4_3',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='img4_4',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='img4_5',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='img5_2',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='img5_3',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='img5_4',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='img5_5',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='img6_2',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='img6_3',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='img6_4',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='img6_5',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='img7_2',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='img7_3',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='img7_4',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='img7_5',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='carousel_1',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='carousel_2',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='carousel_3',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img1_1',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img2_1',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img3_1',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img4_1',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img5_1',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img6_1',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img7_1',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
    ]
