# Generated by Django 3.0.5 on 2020-07-21 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200720_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
