# Generated by Django 3.0.5 on 2020-07-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200726_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img1_1_class',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
