# Generated by Django 3.0.5 on 2020-07-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img3_2_class',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='img3_3_class',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='img3_4_class',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='img3_5_class',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
