from django.db import models
from django.urls import reverse

# Create your models here.


class Post(models.Model):
    visible = models.BooleanField(default=False)
    title = models.CharField(max_length=150)
    subtitle = models.CharField(blank=True, max_length=100)
    author = models.CharField(max_length=100)
    date = models.DateField()
    banner = models.ImageField(upload_to='blog/%Y/%m/%d')
    thumbnail = models.ImageField(upload_to='blog/%Y/%m/%d')
    category = models.CharField(max_length=250)
    description = models.CharField(max_length=250, default="Keeb&Code")

    heading_1 = models.CharField(blank=True, max_length=200)
    p1_1 = models.TextField(blank=True)
    img1_1 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img1_1_class = models.CharField(blank=True, max_length=50)
    caption1_1 = models.CharField(blank=True, max_length=250)
    p1_2 = models.TextField(blank=True)
    img1_2 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img1_2_class = models.CharField(blank=True, max_length=50)
    caption1_2 = models.CharField(blank=True, max_length=250)
    p1_3 = models.TextField(blank=True)
    img1_3 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img1_3_class = models.CharField(blank=True, max_length=50)
    caption1_3 = models.CharField(blank=True, max_length=250)
    p1_4 = models.TextField(blank=True)
    img1_4 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img1_4_class = models.CharField(blank=True, max_length=50)
    caption1_4 = models.CharField(blank=True, max_length=250)
    p1_5 = models.TextField(blank=True)
    img1_5 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img1_5_class = models.CharField(blank=True, max_length=50)
    caption1_5 = models.CharField(blank=True, max_length=250)

    heading_2 = models.CharField(blank=True, max_length=200)
    p2_1 = models.TextField(blank=True)
    img2_1 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img2_1_class = models.CharField(blank=True, max_length=50)
    caption2_1 = models.CharField(blank=True, max_length=250)
    p2_2 = models.TextField(blank=True)
    img2_2 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img2_2_class = models.CharField(blank=True, max_length=50)
    caption2_2 = models.CharField(blank=True, max_length=250)
    p2_3 = models.TextField(blank=True)
    img2_3 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img2_3_class = models.CharField(blank=True, max_length=50)
    caption2_3 = models.CharField(blank=True, max_length=250)
    p2_4 = models.TextField(blank=True)
    img2_4 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img2_4_class = models.CharField(blank=True, max_length=50)
    caption2_4 = models.CharField(blank=True, max_length=250)
    p2_5 = models.TextField(blank=True)
    img2_5 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img2_5_class = models.CharField(blank=True, max_length=50)
    caption2_5 = models.CharField(blank=True, max_length=250)

    heading_3 = models.CharField(blank=True, max_length=200)
    p3_1 = models.TextField(blank=True)
    img3_1 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img3_1_class = models.CharField(blank=True, max_length=50)
    caption3_1 = models.CharField(blank=True, max_length=250)
    p3_2 = models.TextField(blank=True)
    img3_2 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img3_2_class = models.CharField(blank=True, max_length=50)
    caption3_2 = models.CharField(blank=True, max_length=250)
    p3_3 = models.TextField(blank=True)
    img3_3 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img3_3_class = models.CharField(blank=True, max_length=50)
    caption3_3 = models.CharField(blank=True, max_length=250)
    p3_4 = models.TextField(blank=True)
    img3_4 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img3_4_class = models.CharField(blank=True, max_length=50)
    caption3_4 = models.CharField(blank=True, max_length=250)
    p3_5 = models.TextField(blank=True)
    img3_5 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img3_5_class = models.CharField(blank=True, max_length=50)
    caption3_5 = models.CharField(blank=True, max_length=250)

    heading_4 = models.CharField(blank=True, max_length=200)
    p4_1 = models.TextField(blank=True)
    img4_1 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img4_1_class = models.CharField(blank=True, max_length=50)
    caption4_1 = models.CharField(blank=True, max_length=250)
    p4_2 = models.TextField(blank=True)
    img4_2 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img4_2_class = models.CharField(blank=True, max_length=50)
    caption4_2 = models.CharField(blank=True, max_length=250)
    p4_3 = models.TextField(blank=True)
    img4_3 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img4_3_class = models.CharField(blank=True, max_length=50)
    caption4_3 = models.CharField(blank=True, max_length=250)
    p4_4 = models.TextField(blank=True)
    img4_4 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img4_4_class = models.CharField(blank=True, max_length=50)
    caption4_4 = models.CharField(blank=True, max_length=250)
    p4_5 = models.TextField(blank=True)
    img4_5 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img4_5_class = models.CharField(blank=True, max_length=50)
    caption4_5 = models.CharField(blank=True, max_length=250)

    heading_5 = models.CharField(blank=True, max_length=200)
    p5_1 = models.TextField(blank=True)
    img5_1 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img5_1_class = models.CharField(blank=True, max_length=50)
    caption5_1 = models.CharField(blank=True, max_length=250)
    p5_2 = models.TextField(blank=True)
    img5_2 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img5_2_class = models.CharField(blank=True, max_length=50)
    caption5_2 = models.CharField(blank=True, max_length=250)
    p5_3 = models.TextField(blank=True)
    img5_3 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img5_3_class = models.CharField(blank=True, max_length=50)
    caption5_3 = models.CharField(blank=True, max_length=250)
    p5_4 = models.TextField(blank=True)
    img5_4 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img5_4_class = models.CharField(blank=True, max_length=50)
    caption5_4 = models.CharField(blank=True, max_length=250)
    p5_5 = models.TextField(blank=True)
    img5_5 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img5_5_class = models.CharField(blank=True, max_length=50)
    caption5_5 = models.CharField(blank=True, max_length=250)

    heading_6 = models.CharField(blank=True, max_length=200)
    p6_1 = models.TextField(blank=True)
    img6_1 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img6_1_class = models.CharField(blank=True, max_length=50)
    caption6_1 = models.CharField(blank=True, max_length=250)
    p6_2 = models.TextField(blank=True)
    img6_2 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img6_2_class = models.CharField(blank=True, max_length=50)
    caption6_2 = models.CharField(blank=True, max_length=250)
    p6_3 = models.TextField(blank=True)
    img6_3 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img6_3_class = models.CharField(blank=True, max_length=50)
    caption6_3 = models.CharField(blank=True, max_length=250)
    p6_4 = models.TextField(blank=True)
    img6_4 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img6_4_class = models.CharField(blank=True, max_length=50)
    caption6_4 = models.CharField(blank=True, max_length=250)
    p6_5 = models.TextField(blank=True)
    img6_5 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img6_5_class = models.CharField(blank=True, max_length=50)
    caption6_5 = models.CharField(blank=True, max_length=250)

    heading_7 = models.CharField(blank=True, max_length=200)
    p7_1 = models.TextField(blank=True)
    img7_1 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img7_1_class = models.CharField(blank=True, max_length=50)
    caption7_1 = models.CharField(blank=True, max_length=250)
    p7_2 = models.TextField(blank=True)
    img7_2 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img7_2_class = models.CharField(blank=True, max_length=50)
    caption7_2 = models.CharField(blank=True, max_length=250)
    p7_3 = models.TextField(blank=True)
    img7_3 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img7_3_class = models.CharField(blank=True, max_length=50)
    caption7_3 = models.CharField(blank=True, max_length=250)
    p7_4 = models.TextField(blank=True)
    img7_4 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img7_4_class = models.CharField(blank=True, max_length=50)
    caption7_4 = models.CharField(blank=True, max_length=250)
    p7_5 = models.TextField(blank=True)
    img7_5 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    img7_5_class = models.CharField(blank=True, max_length=50)
    caption7_5 = models.CharField(blank=True, max_length=250)

    link = models.CharField(blank=True, max_length=100)
    link_url = models.URLField(blank=True)

    carousel_1 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    carousel_2 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')
    carousel_3 = models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')

    def __str__(self):
        return '%s | %s' % (self.title, str(self.date))

    def get_absolute_url(self):
        return reverse("post-detail", kwargs={id: self.id})
